#!/usr/bin/env zsh

# Super cool keyboard stuffs.
# Required for x applications
setxkbmap -option caps:ctrl_modifier

die () {
    echo >&2 "$@"
    exit 1
}

addToPath() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$PATH:$1
    fi
}

addToPathFront() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$1:$PATH
    fi
}

commitDotFiles() {
    pushd $DOTFILES
    git add .
    git commit -m "automagic messaging from me in the past."
    git push origin main
    popd
}
