#!/usr/bin/env bash

MY_PATH=~/ansible/scripts/

selected=`cat $MY_PATH.cht-lang $MY_PATH.cht-cmd | fzf`
if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter Query: " query

if grep -qs "$selected" $MY_PATH.cht-lang; then
    query=`echo $query | tr ' ' '+'`
    echo \"curl cht.sh/$selected/$query/\" & curl cht.sh/$selected/$query & while [ : ]; do sleep 1; done
else
    curl -s cht.sh/$selected~$query | less
fi

